{
 "title": "Diversity and Enterprise - Interactive Dashboard",
 "description": "Dashboard which provides multiple diversity factors regarding an enterprise.",
 "time": { "from": "2022-05-15T22:00:22.690Z", "to": "2022-05-16T04:00:22.690Z" },
 "templating": {
  "list": [
   {
    "name": "Enterprise",
    "query": "  select distinct [BusinessName] FROM [dbo].[tblBusiness]"
   }
  ]
 },
 "panels": [
  {
   "title": "Organization",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\r\n      a.[BusinessName]\r\n      \r\n  from [dbo].[tblBusiness] a\r\n  \r\n  where [BusinessName] = '$Enterprise'\r\n"
    }
   ]
  },
  {
   "title": "Ownership Details",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n  a.[BusinessName]\r\n      ,a.[OwnershipType]\r\n      ,a.[isWomenOwned] as 'Women Owned'\r\n      ,a.[MBE]\r\n      ,a.[WBE]\r\n      ,a.[MWBE]\r\n      ,a.[LGBTBE]\r\n      ,a.[VOSB]\r\n      ,a.[VeteranOwned]\r\n      \r\n  from [dbo].[tblBusiness] a\r\n  --inner join [dbo].[tblEmployees] b on a.[busID] = b.[busID]\r\n  where [BusinessName] = '$Enterprise'\r\n"
    }
   ]
  },
  {
   "title": "Organization Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": " select\r\n      --a.[BusinessName]\r\n      a.[Address]\r\n      ,a.[City]\r\n      ,a.[State]\r\n      ,a.[Zip]\r\n      ,a.[Country]\r\n      ,a.[PhoneNumber]\r\n      ,a.[BusType]\r\n  from [dbo].[tblBusiness] a\r\n  --inner join [dbo].[tblEmployees] b on a.[busID] = b.[busID]\r\n  where [BusinessName] = '$Enterprise'"
    }
   ]
  },
  {
   "title": "Employee Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select\r\n  --a.BusinessName\r\n  b.Datasource\r\n  ,b.Name as Employee\r\n  ,b.Designation\r\n  ,b.gender\r\n  ,b.MaritalStatus\r\n  ,b.Race\r\n  ,b.Ethnicity\r\n  ,b.Education\r\n  ,b.Language\r\n  ,b.Nationality\r\n  ,b.Disability\r\n    from [dbo].[tblBusiness] a\r\n  inner join [dbo].[tblEmployees] b on a.[busID] = b.[busID]\r\n  where [BusinessName] = '$Enterprise'"
    }
   ]
  }
 ]
}