{
 "title": "Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Ethnicity Based Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Business ownership Based on Ethnicity",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  select count(*), [OwnershipType]\r\n  from [dbo].[tblBusiness]\r\n  where not [OwnershipType] = 'NULL'\r\n  group by [OwnershipType]"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "  select count(*), [OwnershipType]\r\n  from [dbo].[tblBusiness]\r\n  where not [OwnershipType] = 'NULL'\r\n  group by [OwnershipType]"
    }
   ]
  },
  { "title": "Gender Based Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Business Owned by",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select count(a.[WBE]) as 'Women Owned'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[WBE] = 'Yes'\r\n  group by a.[WBE]"
    },
    {
     "rawSql": "select count(a.[MBE]) as 'Men Owned'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[MBE] = 'Yes'\r\n  group by a.[MBE]"
    },
    {
     "rawSql": "select count(a.[MWBE]) as 'Minority Women Owned'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[MWBE] = 'Yes'\r\n  group by a.[MWBE]"
    },
    {
     "rawSql": "  select count(a.[LGBTBE]) as 'LGBT Owned'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[LGBTBE] = 'Yes'\r\n  group by a.[LGBTBE]"
    },
    {
     "rawSql": "    select count(a.[VOSB]) as 'Veteran Owned Small Business'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[VOSB] = 'Yes'\r\n  group by a.[VOSB]"
    },
    {
     "rawSql": "    select count(a.[VeteranOwned]) as 'Veteran Owned'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[VeteranOwned] = 'Yes'\r\n  group by a.[VeteranOwned]"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select count(a.[WBE]) as 'Women Owned'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[WBE] = 'Yes'\r\n  group by a.[WBE]"
    },
    {
     "rawSql": "select count(a.[MBE]) as 'Men Owned'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[MBE] = 'Yes'\r\n  group by a.[MBE]"
    },
    {
     "rawSql": "select count(a.[MWBE]) as MWBE\r\n  from [dbo].[tblBusiness] a\r\n  where a.[MWBE] = 'Yes'\r\n  group by a.[MWBE]"
    },
    {
     "rawSql": "  select count(a.[LGBTBE]) as 'LGBT owned'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[LGBTBE] = 'Yes'\r\n  group by a.[LGBTBE]"
    },
    {
     "rawSql": "    select count(a.[VOSB]) as 'Veteran Owned Small Business'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[VOSB] = 'Yes'\r\n  group by a.[VOSB]"
    },
    {
     "rawSql": "    select count(a.[VeteranOwned]) as 'Veteran Owned'\r\n  from [dbo].[tblBusiness] a\r\n  where a.[VeteranOwned] = 'Yes'\r\n  group by a.[VeteranOwned]"
    }
   ]
  },
  { "title": "Organization Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Employee Details",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "select\r\n  a.BusinessName\r\n  ,b.Datasource\r\n  ,b.Name as Employee\r\n  ,b.Designation\r\n  ,b.gender\r\n  ,b.MaritalStatus\r\n  ,b.Race\r\n  ,b.Ethnicity\r\n  ,b.Education\r\n  ,b.Language\r\n  ,b.Nationality\r\n  ,b.Disability\r\n    from [dbo].[tblBusiness] a\r\n  inner join [dbo].[tblEmployees] b on a.[busID] = b.[busID]\r\n  --where [BusinessName] = '$Enterprise'\r\n  order by [BusinessName]"
    }
   ]
  },
  {
   "title": "Companies vs State ",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "\r\n    select [State], count(*) \r\n  from [dbo].[tblBusiness]\r\n  where not [Country] = 'NULL'\r\n  group by [State]"
    }
   ]
  }
 ]
}